### ISSUE TITLE
Model Finetuning

### ISSUE THREAD

**Issue by donjuanpond** [arvindrajan92/DTrOCR#14]
Just wanted to ask, are you working on creating a finetuning script for this model? If so, when do you plan on releasing it?

**Comment by arvindrajan92** [comment]
hello @donjuanpond, there is no script as such, but there is a finetuning example [here](https://github.com/arvindrajan92/DTrOCR/blob/main/examples/IAMFineTune.ipynb) - hope you'll find this useful. also note that the model has not been pre-trained, hence you may not get the expected performance.

currently, i am doing the groundwork to pre-train on printed and handwritten texts. script for fine-tuning would come later.

**Comment by arvindrajan92** [comment]
@donjuanpond are you happy for me to close this issue? or do you need assistance?

**Comment by donjuanpond** [comment]
Sorry for not closing myself, everything seems good!
